import "@/app/globals.css";
import SideLayout from "@/components/sideLayout";
import TopBar from "@/components/topbar";
import { getSession } from "@/lib/session";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getSession();
  return (
    <SideLayout userSession={session}>
      <TopBar isLoggedIn={!!session}>{children}</TopBar>
    </SideLayout>
  );
}
